SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[persons](
	[id] [int] NOT NULL,
	[person_name] [varchar](50) NOT NULL,
	[date_of_birth] [date] NULL,
	[phone] [varchar](11) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[persons] ADD  CONSTRAINT [pk_persons] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
